
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.io.*;

import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class FeedPanel extends JPanel {                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                               
        //Things to do - Keep a list record in a file                                                                                                                                                                                                                                                                          
        DefaultListModel listModel = new DefaultListModel();                                                                                                                                                                                                                                                                   
        JButton save = new JButton("Save");                                                                                                                                                                                                                                                                                    
        JButton addRSS = new JButton("Add RSS");                                                                                                                                                                                                                                                                               
        JButton removeRSS = new JButton("Remove RSS");                                                                                                                                                                                                                                                                         
        JButton openFeed = new JButton("OpenFeed");                                                                                                                                                                                                                                                                            
        JList feedList = new JList(listModel);                                                                                                                                                                                                                                                                                 
        ArrayList<String> feedNames = new ArrayList<String>();                                                                                                                                                                                                                                                                                           
        BufferedWriter output;                                                                                                                                                                                                                                                                                                 
        BufferedReader input;                                                                                                                                                                                                                                                                                                  
        MainPanel main;                  
        JPanel top = new JPanel();
                                                                                                                                                                                                                                                                                                                               
        public FeedPanel(MainPanel parent) throws IOException                                                                                                                                                                                                                                                                  
        {               
        		top.setLayout(new FlowLayout());
        		top.add(addRSS);
        		top.add(removeRSS);
        		top.add(openFeed);
        		top.add(save);
        		top.setSize(320, 50);
        		top.setBackground(Color.WHITE);
        		this.add(top,BorderLayout.NORTH);
        		this.add(feedList,BorderLayout.CENTER);
        		this.setVisible(true);
        		
                main = parent;                                                                                                                                                                                                                                                                                                 
                //################load begin                                                                                                                                                                                                                                                                                   
                             
                File inputFile = new File("feeds.txt");
                if (!inputFile.exists()) {
                	inputFile.createNewFile();
                }
                input = new BufferedReader(new FileReader(inputFile));                                                                                                                                                                                                                                                       
                if (input.ready()) {                                                                                                                                                                                                                                                                                         
                	load();             
                }
                //                                                                                                                                                                                                                                                                                                             
                input.close();                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                               
                //############load complete                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                               
                addRSS.addActionListener(new ActionListener()                                                                                                                                                                                                                                                                  
                {                                                                                                                                                                                                                                                                                                              
                        public void actionPerformed(ActionEvent e)                                                                                                                                                                                                                                                             
                        {                                                                                                                                                                                                                                                                                                      
                                addFeed();                                                                                                                                                                                                                                                                                     
                        }                                                                                                                                                                                                                                                                                                      
                });                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                               
                save.addActionListener(new ActionListener()                                                                                                                                                                                                                                                                    
                {                                                                                                                                                                                                                                                                                                              
                        public void actionPerformed(ActionEvent e)                                                                                                                                                                                                                                                             
                        {                                                                                                                                                                                                                                                                                                      
                                try {                                                                                                                                                                                                                                                                                          
                                        save();                                                                                                                                                                                                                                                                                
                                } catch (IOException e1) {                                                                                                                                                                                                                                                                     
                                        e1.printStackTrace();                                                                                                                                                                                                                                                                  
                                }                                                                                                                                                                                                                                                                                              
                        }                                                                                                                                                                                                                                                                                                      
                });                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                               
                //used to remove the selected index                                                                                                                                                                                                                                                                            
                removeRSS.addActionListener(new ActionListener()                                                                                                                                                                                                                                                               
                {                                                                                                                                                                                                                                                                                                              
                        public void actionPerformed(ActionEvent e)                                                                                                                                                                                                                                                             
                        {                                                                                                                                                                                                                                                                                                      
                                if (feedList.getSelectedIndex()!=-1)                                                                                                                                                                                                                                                           
                                        feedList.remove(feedList.getSelectedIndex());                                                                                                                                                                                                                                          
                        }                                                                                                                                                                                                                                                                                                      
                });                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                               
                openFeed.addActionListener(new ActionListener()                                                                                                                                                                                                                                                                
                {                                                                                                                                                                                                                                                                                                              
                        public void actionPerformed(ActionEvent e)                                                                                                                                                                                                                                                             
                        {                                                                                                                                                                                                                                                                                                      
                                if (feedList.getSelectedIndex()!=-1)                                                                                                                                                                                                                                                           
                                        openFeed(feedList.getSelectedIndex());                                                                                                                                                                                                                                                 
                        }                                                                                                                                                                                                                                                                                                      
                });                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                               
                feedList.addListSelectionListener(new ListSelectionListener()    
                {                                                                                                                                                                                                                                                                                                              
                    public void valueChanged(ListSelectionEvent e)                                                                                                                                                                                                                                                         
                    {                                                                                                                                                                                                                                                                                                      
                            //if a feed is selected                                                                                                                                                                                                                                                                        
                            if (!(feedList.isSelectionEmpty()))                                                                                                                                                                                                                                                            
                            {                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                           
                            }                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                           
                    }                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                           
            });                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                           
    }                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                           
    //will have a input dialog for the url                                                                                                                                                                                                                                                                                 
    public void addFeed()                                                                                                                                                                                                                                                                                                  
    {                                                                                                                                                                                                                                                                                                                      
            String addURL,addName;                                                                                                                                                                                                                                                                                         
            addURL = JOptionPane.showInputDialog("Enter a URL");                                                                                                                                                                                                                                                           
            //do a check for if it's valid                                                                                                                                                                                                                                                                                 
            if (RSSParser.isValid(addURL))                                                                                                                                                                                                                                                                                       
            {                                                                                                                                                                                                                                                                                                              
                    feedNames.add(addURL);//for accessing url names                                                                                                                                                                                                                                                        
                    //add the name of the feed to the list                                                                                                                                                                                                                                                                 
                    addName = JOptionPane.showInputDialog("Enter a name for your feed");                                                                                                                                                                                                                                   
                    //name to be displayed in list                                                                                                                                                                                                                                                                         
                    listModel.addElement(addName);                                                                                                                                                                                                                                                                         
            }                                                                                                                                                                                                                                                                                                              
            else                                                                                                                                                                                                                                                                                                           
            {                                                                                                                                                                                                                                                                                                              
                    JOptionPane.showMessageDialog(null, "URL not valid");                                                                                                                                                                                                                                                  
            }                                                                                                                                                                                                                                                                                                              
    }                                                                                                                                                                                                                                                                                                                      
    public void removeFeed(int index)                                                                                                                                                                                                                                                                                      
    {                                                                                                                                                                                                                                                                                                                      
            listModel.remove(index);                                                                                                                                                                                                                                                                                       
            feedNames.remove(index);                                                                                                                                                                                                                                                                                       
    }                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                           
    public void load() throws IOException                                                                                                                                                                                                                                                                                  
    {                                                                                                                                                                                                                                                                                                                      
            String line;                                                                                                                                                                                                                                                                                                   
            StringTokenizer token;                                                                                                                                                                                                                                                                                         
            while ((line=input.readLine())!=null)                                                                                                                                                                                                                                                                          
            {                                                                                                                                                                                                                                                                                                              
                    token = new StringTokenizer(line,",");  //tokenizes the line                                                                                                                                                                                                                                           
                    listModel.addElement(token.nextToken()); //gets the name                                                                                                                                                                                                                                               
                    feedNames.add(token.nextToken());        //gets the url                                                                                                                                                                                                                                                
            }                                                                                                                                                                                                                                                                                                              
    }                                                                                                                                                                                                                                                                                                                      
    public void save() throws IOException                                                                                                                                                                                                                                                                                  
    {                                                                                                                                                                                                                                                                                                                      
            BufferedWriter output=new BufferedWriter(new FileWriter("feeds.txt"));                                                                                                                                                                                                                                         
            String line="";                                                                                                                                                                                                                                                                                                
            for(int i=0;i<feedNames.size();++i)                                                                                                                                                                                                                                                                            
            {                                                                                                                                                                                                                                                                                                              
                    //will write the name and url of feed at position i                                                                                                                                                                                                                                                    
                    //to line and add a new line character                                                                                                                                                                                                                                                                 
                    line += listModel.get(i) + "," + feedNames.get(i) + "\n";                                                                                                                                                                                                                                              
            }                                                                                                                                                                                                                                                                                                              
            output.write(line); 
            output.close();
    }                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                           
    public void openFeed(int index)                                                                                                                                                                                                                                                                                        
    {                                                                                                                                                                                                                                                                                                                      
            main.openFeed(feedNames.get(index), (String)listModel.get(index));                                                                                                                                                                                                                                             
    }                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                           
}
