import javax.swing.JPanel;
import javax.swing.JTabbedPane;

public class RSSDisplay extends JPanel implements Runnable                                                                                                                                                                                                                                                                     
{                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                               
        public RSSDisplay(String URL)                                                                                                                                                                                                                                                                                          
        {                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                               
        }                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                               
        public void run()                                                                                                                                                                                                                                                                                                      
        {                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                               
        }                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                               
}
